### ISSUE TITLE
Vanilla ImageJ2 is missing libraries

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej#130]
When starting up a plain ImageJ2:
```
[ERROR] Cannot create plugin: class='net.imagej.ui.swing.script.languagesupport.JavaScriptLanguageSupportPlugin', priority=0.0, enabled=true, pluginType=LanguageSupportPlugin
java.lang.NoClassDefFoundError: org/fife/ui/autocomplete/AutoCompletion
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:302)
	at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:236)
	at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:225)
	at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:216)
	at org.scijava.plugin.AbstractSingletonService.initInstances(AbstractSingletonService.java:123)
	at org.scijava.plugin.AbstractSingletonService.getInstances(AbstractSingletonService.java:72)
	at org.scijava.plugin.AbstractSingletonService$1.get(AbstractSingletonService.java:101)
	at org.scijava.plugin.AbstractSingletonService$1.get(AbstractSingletonService.java:97)
	at org.scijava.object.ObjectIndex.resolvePending(ObjectIndex.java:387)
	at org.scijava.object.ObjectIndex.get(ObjectIndex.java:132)
	at org.scijava.object.DefaultObjectService.getObjects(DefaultObjectService.java:86)
	at org.scijava.display.DefaultDisplayService.getDisplays(DefaultDisplayService.java:165)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:182)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:165)
	at net.imagej.Main.launch(Main.java:67)
	at net.imagej.Main.main(Main.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:258)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:184)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:76)
Caused by: java.lang.ClassNotFoundException: org.fife.ui.autocomplete.AutoCompletion
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
```
The JAR(s) in question should be migrated from the Fiji update site to the ImageJ update site.

**Comment by ctrueden** [comment]
I released `2.0.0-rc-39` and uploaded all the newly needed libraries, including the `librarysupport` JAR and others.
