### ISSUE TITLE
Make ImageJ2 run successfully with Java 9

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej#155]
Attempting to launch ImageJ2, either with or without the Fiji extensions, does not work with a recent Java 9 prerelease.

First of all, the Launcher adds some JVM arguments which are no longer supported by Java 9. Removing those arguments from the launch command results in something like this:
```
java -Dpython.cachedir.skip=true -Dplugins.dir=$PATH_FIJI_USER -Xmx10420m -Djava.class.path=$PATH_FIJI_USER/jars/imagej-launcher-4.0.5.jar -Dimagej.dir=$PATH_FIJI_USER -Dij.dir=$PATH_FIJI_USER -Dfiji.dir=$PATH_FIJI_USER -Dfiji.executable=$FIJI_EXEC -Dij.executable=$FIJI_EXEC -Djava.library.path=$PATH_FIJI_USER/lib/macosx:$PATH_FIJI_USER/mm/macosx net.imagej.launcher.ClassLauncher -ijjarpath jars -ijjarpath plugins net.imagej.Main
```

But then there are errors relating to the IJ1 class patching (ij1-patcher and imagej-legacy).
```
Error while executing the main() method of class 'net.imagej.Main':
java.lang.IllegalArgumentException: Invalid service: net.imagej.legacy.LegacyConsoleService
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:280)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:231)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:166)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:76)
	at net.imagej.Main.launch(Main.java:61)
	at net.imagej.Main.main(Main.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:538)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Caused by: java.lang.IllegalArgumentException: Invalid service: net.imagej.legacy.LegacyService
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:280)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:231)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:340)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:269)
	... 17 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:461)
	at java.base/java.lang.Class.newInstance(Class.java:563)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:302)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:269)
	... 20 more
Caused by: java.lang.RuntimeException: No _hooks field found in ij.IJ
It appears that this class was already defined in the class loader!
Please make sure that you initialize the LegacyService before using
any ImageJ 1.x class. You can do that by adding this static initializer:

	static {
		LegacyInjector.preinit();
	}

To debug this issue, start the JVM with the option:

	-javaagent:/Applications/Fiji.app/jars/ij1-patcher-0.12.5.jar

To enforce pre-initialization, start the JVM with the option:

	-javaagent:/Applications/Fiji.app/jars/ij1-patcher-0.12.5.jar=init

	at net.imagej.patcher.CodeHacker.javaAgentHint(CodeHacker.java:828)
	at net.imagej.patcher.LegacyInjector.alreadyPatched(LegacyInjector.java:433)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:380)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:131)
	... 27 more
Caused by: java.lang.NoSuchFieldException: _hooks
	at java.base/java.lang.Class.getField(Class.java:1889)
	at net.imagej.patcher.LegacyInjector.alreadyPatched(LegacyInjector.java:424)
	... 30 more
```

I briefly attempted to debug by adding ij1-patcher as a javaagent as described above, but it says:
```
Unknown option: -javaagent:/Applications/Fiji.app/jars/ij1-patcher-0.12.5.jar!
```
Maybe Java 9 does not implement that yet?

Note that if you remove `jars/imagej-legacy-*.jar` first, then the above invocation works successfully to start up ImageJ2 with the Swing UI, and everything (in my basic tests) works.

**Comment by rogersachan** [comment]
@ctrueden See the [Java 9 migration guide](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-7744EF96-5899-4FB2-B34E-86D49B2E89B6) by Oracle.

**Comment by ctrueden** [comment]
@rogersachan Thanks. However, I saw no mention of the `-javaagent` flag in that guide. From jboss-javassist/javassist@6a3ed31976e54f2523a6e41dfee9001b3cce58c8, I infer that: 1) Java 9 prerelease builds are still changing enough that Javassist needs modification to keep pace; and 2) you must now pass special flags to the JVM in order to allow Javassist to do its thing.

I think I will wait till Java 9's first official release before pursuing this issue.

**Comment by paulmenzel** [comment]
[Java 9 was released in September 2017.](http://www.oracle.com/technetwork/java/javase/9all-relnotes-3704433.html)

With ImageJ 1.51n and Java 9, I get the error below, and it doesn’t start.

```
$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
$ /opt/Fiji.app/ImageJ-linux64 --system # ImageJ launcher 4.0.5 (build 1260)
Warning: falling back to system Java
Unrecognized option: -Xincgc
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by paulmenzel** [comment]
No idea, how to override the Java options. `--help` does not list environment variables. But there is the switch `default-gc` disabling the problematic option `Xincgc`, which, according to the manual, is already deprecated is Java 8 with no replacement.

Passing `--default-gc` to ImageJ and starting it with Java 9.0.1, warnings are printed to the terminal, but it starts (and is correctly scaled with `GDK_SCALE=2 GDK_DPI_SCALE=-1` on HiDPI displays).

```
$ /opt/Fiji.app/ImageJ-linux64 --system --default-gc
Warning: falling back to system Java
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.imagej.patcher.LegacyInjector (file:/scratch/local/Fiji.app/jars/ij1-patcher-0.12.6.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of net.imagej.patcher.LegacyInjector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ERROR] Exception during event handling:
	[Event] org.scijava.service.event.ServicesLoadedEvent
	context = org.scijava.Context@4f654cee
	consumed = false
	[Subscriber] fiji.DefaultFijiService [priority = 0.0]
	[Method] protected void fiji.DefaultFijiService.onEvent(org.scijava.service.event.ServicesLoadedEvent)
java.lang.NoSuchMethodError: java.awt.MenuBar.getPeer()Ljava/awt/peer/MenuComponentPeer;
	at fiji.IJ_Alt_Key_Listener.getX11Opener(IJ_Alt_Key_Listener.java:98)
	at fiji.IJ_Alt_Key_Listener.getOpener(IJ_Alt_Key_Listener.java:87)
	at fiji.IJ_Alt_Key_Listener.<init>(IJ_Alt_Key_Listener.java:18)
	at fiji.DefaultFijiService.actuallyInitialize(DefaultFijiService.java:55)
	at fiji.DefaultFijiService.onEvent(DefaultFijiService.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:300)
	at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:274)
	at org.bushe.swing.event.ThreadSafeEventService.publish(ThreadSafeEventService.java:971)
	at org.scijava.event.DefaultEventBus.access$201(DefaultEventBus.java:56)
	at org.scijava.event.DefaultEventBus$2.run(DefaultEventBus.java:216)
	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:220)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by ctrueden** [comment]
Thanks to @stelfrich's efforts (see imagej/imagej-launcher#52), current builds of the ImageJ launcher are now able to launch ImageJ2 with Java 9 or 10. However, there are still some annoyances; see #197.
