### ISSUE TITLE
Fresh downloaded Fiji does not startup on Windows7 x64

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/imagej#160]
Hey guys,

I just downloaded a fresh Fiji. When starting it, it closes after some seconds. When running it as debug.exe, it says 
```
[DEBUG] Created service 'org.scijava.app.DefaultAppService' in 2 ms
[DEBUG] Creating service: org.scijava.parse.DefaultParseService
[DEBUG] Created service 'org.scijava.parse.DefaultParseService' in 1 ms
[DEBUG] Created service 'org.scijava.script.DefaultScriptService' in 10 ms
[DEBUG] Creating service: org.scijava.app.DefaultStatusService
[DEBUG] Created service 'org.scijava.app.DefaultStatusService' in 1 ms
[DEBUG] Creating service: io.scif.services.SCIFIODatasetService
[DEBUG] Created service 'io.scif.services.SCIFIODatasetService' in 6 ms
[DEBUG] Creating service: org.scijava.display.DefaultDisplayService
[DEBUG] Created service 'org.scijava.display.DefaultDisplayService' in 3 ms
[DEBUG] Creating service: org.scijava.menu.DefaultMenuService
[DEBUG] Created service 'org.scijava.menu.DefaultMenuService' in 2 ms
[DEBUG] Creating service: net.imagej.display.DefaultOverlayService
[DEBUG] Creating service: net.imagej.ui.awt.AWTRenderingService
[DEBUG] Created service 'net.imagej.ui.awt.AWTRenderingService' in 1 ms
[DEBUG] Created service 'net.imagej.display.DefaultOverlayService' in 7 ms
[DEBUG] Creating service: net.imagej.threshold.DefaultThresholdService
[DEBUG] Created service 'net.imagej.threshold.DefaultThresholdService' in 3 ms
[DEBUG] Found 6 App plugins.
[DEBUG] Found 10 ScriptLanguage plugins.
[DEBUG] Not overwriting name 'Clojure':
        proposed = org.scijava.plugins.scripting.clojure.ClojureScriptLanguage
        existing = org.scijava.plugins.scripting.clojure.ClojureScriptLanguage
[DEBUG] Not overwriting name 'Java':
        proposed = org.scijava.plugins.scripting.java.JavaScriptLanguage
        existing = org.scijava.plugins.scripting.java.JavaScriptLanguage
[DEBUG] Not overwriting name 'JavaScript':
        proposed = org.scijava.plugins.scripting.javascript.JavaScriptScriptLang
uage
        existing = org.scijava.plugins.scripting.javascript.JavaScriptScriptLang
uage
[DEBUG] Ignoring unsupported script: trackmateGraph.m
[DEBUG] Ignoring unsupported script: Miji.m
[DEBUG] Ignoring unsupported script: trackmateSpots.m
[DEBUG] Ignoring unsupported script: Matlab3DViewerDemo_3.m
[DEBUG] Ignoring unsupported script: Matlab3DViewerDemo_2.m
[DEBUG] Ignoring unsupported script: Matlab3DViewerDemo_1.m
[DEBUG] Ignoring unsupported script: Matlab3DViewerIntroduction.m
[DEBUG] Ignoring unsupported script: copytoImg.m
[DEBUG] Ignoring unsupported script: trackmateFeatureDeclarations.m
[DEBUG] Ignoring unsupported script: ImageJ.m
[DEBUG] Ignoring unsupported script: Miji_Test.m
[DEBUG] Ignoring unsupported script: InstallJava3D.m
[DEBUG] Ignoring unsupported script: trackmateImageCalibration.m
[DEBUG] Ignoring unsupported script: copytoImgPlus.m
[DEBUG] Ignoring unsupported script: IsJava3DInstalled.m
[DEBUG] Ignoring unsupported script: trackmateEdges.m
[DEBUG] Ignoring unsupported script: importTrackMateTracks.m
[DEBUG] Ignoring unsupported script: copytoMatlab.m
[DEBUG] Ignoring unsupported script: bfopen.m
[DEBUG] Ignoring unsupported script: Series_Labeler-2.0.0.jar
[DEBUG] Ignoring unsupported script: Dichromacy_-2.1.0.jar
[DEBUG] Ignoring unsupported script: Javascript_-2.0.0-SNAPSHOT.jar
[DEBUG] Ignoring unsupported script: Cell_Counter-2.2.1.jar
[DEBUG] Ignoring unsupported script: Auto_Threshold-1.16.4.jar
[DEBUG] Ignoring unsupported script: Gray_Morphology-2.3.3.jar
[DEBUG] Ignoring unsupported script: Macros/Bulls_Eye.txt
[DEBUG] Ignoring unsupported script: TrakEM2_Archipelago-2.0.1.jar
[DEBUG] Ignoring unsupported script: Simple_Neurite_Tracer-3.0.6.jar
[DEBUG] Ignoring unsupported script: Correct_3D_Drift-1.0.0.jar
[DEBUG] Ignoring unsupported script: Fiji_Plugins-3.0.0.jar
[DEBUG] Ignoring unsupported script: CLI_-2.0.0-SNAPSHOT.jar
[DEBUG] Ignoring unsupported script: KymographBuilder-1.2.3.jar
[DEBUG] Ignoring unsupported script: QuickPALM_-1.1.1.jar
[DEBUG] Ignoring unsupported script: Colour_Deconvolution-3.0.1.jar
[DEBUG] Ignoring unsupported script: Time_Lapse-2.0.1.jar
[DEBUG] Ignoring unsupported script: Bug_Submitter-2.1.0.jar
[DEBUG] Ignoring unsupported script: blockmatching_-2.1.1.jar
[DEBUG] Ignoring unsupported script: Siox_Segmentation-1.0.4.jar
[DEBUG] Ignoring unsupported script: registration_3d-2.0.0.jar
[DEBUG] Ignoring unsupported script: Macros/Polygon_.txt
[DEBUG] Ignoring unsupported script: bUnwarpJ_-2.6.4.jar
[DEBUG] Ignoring unsupported script: H5J_Loader_Plugin-1.0.6.jar
[DEBUG] Ignoring unsupported script: Color_Histogram-2.0.6.jar
[DEBUG] Ignoring unsupported script: Differentials_-2.0.0.jar
[DEBUG] Ignoring unsupported script: Refresh_Javas-2.0.0-SNAPSHOT.jar
[DEBUG] Ignoring unsupported script: Descriptor_based_registration-2.1.1.jar
[DEBUG] Ignoring unsupported script: SheppLogan_-2.0.0.jar
[DEBUG] Ignoring unsupported script: Manual_Tracking-2.1.0.jar
[DEBUG] Ignoring unsupported script: register_virtual_stack_slices-3.0.1.jar
[DEBUG] Ignoring unsupported script: VIB_-3.0.1.jar
[DEBUG] Ignoring unsupported script: Archipelago_Plugins-0.5.2.jar
[DEBUG] Ignoring unsupported script: trakem2_tps-1.1.2.jar
[DEBUG] Ignoring unsupported script: TrakEM2_-1.0h.jar
[DEBUG] Ignoring unsupported script: panorama_-3.0.1.jar
[DEBUG] Ignoring unsupported script: View5D_-1.3.1.jar
[DEBUG] Ignoring unsupported script: Extended_Depth_Field-2.0.1.jar
[DEBUG] Ignoring unsupported script: LSM_Toolbox-4.1.1.jar
[DEBUG] Ignoring unsupported script: AnalyzeSkeleton_-3.1.1.jar
[DEBUG] Ignoring unsupported script: Fiji_Updater.jar
[DEBUG] Ignoring unsupported script: Helmholtz_Analysis-2.0.1.jar
[DEBUG] Ignoring unsupported script: IsoData_Classifier-2.0.0.jar
[DEBUG] Ignoring unsupported script: LSM_Reader-4.1.1.jar
[DEBUG] Ignoring unsupported script: BalloonSegmentation_-2.0.0.jar
[DEBUG] Ignoring unsupported script: Vaa3d_Reader-2.0.1.jar
[DEBUG] Ignoring unsupported script: Graph_Cut-1.0.1.jar
[DEBUG] Ignoring unsupported script: bigdataviewer_fiji-3.0.0.jar
[DEBUG] Ignoring unsupported script: Stack_Manipulation-2.0.1.jar
[DEBUG] Ignoring unsupported script: PointPicker_-2.0.0.jar
[DEBUG] Ignoring unsupported script: Jython_Interpreter-2.0.0-SNAPSHOT.jar
[DEBUG] Ignoring unsupported script: Fiji_Archipelago-2.0.0.jar
[DEBUG] Ignoring unsupported script: Kuwahara_Filter-2.0.0.jar
[DEBUG] Ignoring unsupported script: Samples_-2.0.1.jar
[DEBUG] Ignoring unsupported script: Linear_Kuwahara-2.0.0.jar
[DEBUG] Ignoring unsupported script: Macros/batch_convert_any_to_tif.txt
[DEBUG] Ignoring unsupported script: IO_-3.0.1.jar
[DEBUG] Ignoring unsupported script: M_I_P-2.0.0.jar
[DEBUG] Ignoring unsupported script: Colocalisation_Analysis-2.2.1.jar
[DEBUG] Ignoring unsupported script: Statistical_Region_Merging-2.0.0.jar
[DEBUG] Ignoring unsupported script: Time_Stamper-2.0.0.jar
[DEBUG] Ignoring unsupported script: TurboReg_-2.0.0.jar
[DEBUG] Ignoring unsupported script: Arrow_-2.0.1.jar
[DEBUG] Ignoring unsupported script: Image_Expression_Parser-3.0.0.jar
[DEBUG] Ignoring unsupported script: Macros/RGB_Histogram.txt
[DEBUG] Ignoring unsupported script: Image_5D-2.0.1.jar
[DEBUG] Ignoring unsupported script: CorrectBleach_-2.0.1.jar
[DEBUG] Ignoring unsupported script: Interactive_3D_Surface_Plot-2.4.1.jar
[DEBUG] Ignoring unsupported script: Fiji_Package_Maker-2.1.0.jar
[DEBUG] Ignoring unsupported script: 3D_Objects_Counter-2.0.0.jar
[DEBUG] Ignoring unsupported script: Clojure_Interpreter-2.0.0-SNAPSHOT.jar
[DEBUG] Ignoring unsupported script: Sync_Win-1.7-fiji3.jar
[DEBUG] Ignoring unsupported script: readme.txt
[DEBUG] Ignoring unsupported script: Calculator_Plus-2.0.0.jar
[DEBUG] Ignoring unsupported script: ToAST_-25.0.1.jar
[DEBUG] Ignoring unsupported script: z_spacing-0.0.1-SNAPSHOT.jar
[DEBUG] Ignoring unsupported script: JRuby_Interpreter-2.0.0-SNAPSHOT.jar
[DEBUG] Ignoring unsupported script: PIV_analyser-1.1.1.jar
[DEBUG] Ignoring unsupported script: level_sets-1.0.1.jar
[DEBUG] Ignoring unsupported script: Analyze/Measure_RGB.txt
[DEBUG] Ignoring unsupported script: SplineDeformationGenerator_-2.0.0.jar
[DEBUG] Ignoring unsupported script: Reconstruct_Reader-2.0.2.jar
[DEBUG] Ignoring unsupported script: MosaicJ_-2.0.0.jar
[DEBUG] Ignoring unsupported script: Sholl_Analysis-3.6.9.jar
[DEBUG] Ignoring unsupported script: IJ_Robot-2.0.0.jar
[DEBUG] Ignoring unsupported script: Multi_Kymograph-2.0.0.jar
[DEBUG] Ignoring unsupported script: Color_Inspector_3D-2.3.1.jar
[DEBUG] Ignoring unsupported script: SPIM_Registration-5.0.8.jar
[DEBUG] Ignoring unsupported script: Volume_Viewer-2.01.1.jar
[DEBUG] Ignoring unsupported script: Vaa3d_Writer-1.0.1.jar
[DEBUG] Ignoring unsupported script: 3D_Blob_Segmentation-3.0.0.jar
[DEBUG] Ignoring unsupported script: Algorithm_Launcher.jar
[DEBUG] Ignoring unsupported script: FS_Align_TrakEM2-2.0.1.jar
[DEBUG] Ignoring unsupported script: TrackMate_-3.4.2.jar
[DEBUG] Ignoring unsupported script: Directionality_-2.0.1.jar
[DEBUG] Ignoring unsupported script: mpicbg_-1.1.1.jar
[DEBUG] Ignoring unsupported script: 3D_Viewer-4.0.1.jar
[DEBUG] Ignoring unsupported script: LocalThickness_-4.0.1.jar
[DEBUG] Ignoring unsupported script: Fiji_Developer-2.0.5.jar
[DEBUG] Ignoring unsupported script: Anisotropic_Diffusion_2D-2.0.0.jar
[DEBUG] Ignoring unsupported script: Macros/About_Plugin_Macros.txt
[DEBUG] Ignoring unsupported script: Skeletonize3D_-2.1.0.jar
[DEBUG] Ignoring unsupported script: Volume_Calculator-2.0.1.jar
[DEBUG] Ignoring unsupported script: bigwarp_fiji-2.1.5.jar
[DEBUG] Ignoring unsupported script: FlowJ_-1.29.2.jar
[DEBUG] Ignoring unsupported script: Stitching_-3.1.1.jar
[DEBUG] Ignoring unsupported script: Snakuscule_-2.0.0.jar
[DEBUG] Ignoring unsupported script: StackReg_-2.0.0.jar
[DEBUG] Ignoring unsupported script: Feature_Detection-2.0.1.jar
[DEBUG] Ignoring unsupported script: Lasso_and_Blow_Tool-2.0.1.jar
[DEBUG] Ignoring unsupported script: UnwarpJ_-2.0.0.jar
[DEBUG] Ignoring unsupported script: BeanShell_Interpreter-2.0.0-SNAPSHOT.jar
[DEBUG] Ignoring unsupported script: ij-ImageIO_.jar
[DEBUG] Ignoring unsupported script: RATS_-2.0.0.jar
[DEBUG] Ignoring unsupported script: CPU_Meter-2.0.0.jar
[DEBUG] Ignoring unsupported script: MTrack2_-2.0.0.jar
[DEBUG] Ignoring unsupported script: Thread_Killer-2.0.0.jar
[DEBUG] Ignoring unsupported script: Trainable_Segmentation-3.2.2.jar
[DEBUG] Ignoring unsupported script: Video_Editing-2.0.0.jar
[DEBUG] Ignoring unsupported script: TopoJ_-2.0.0.jar
[DEBUG] Ignoring unsupported script: Utilities/Close_All_Without_Saving.txt
[DEBUG] Ignoring unsupported script: bio-formats_plugins-5.3.0.jar
[DEBUG] Ignoring unsupported script: SPIM_Opener-2.0.1.jar
[DEBUG] Found 66 scripts
[DEBUG] Created service 'net.imagej.legacy.LegacyService' in 2593 ms
[DEBUG] Created service 'net.imagej.legacy.LegacyConsoleService' in 2595 ms
[DEBUG] Creating service: fiji.DefaultFijiService
[DEBUG] Created service 'fiji.DefaultFijiService' in 1 ms
[DEBUG] Creating service: org.scijava.console.DefaultConsoleService
[DEBUG] Created service 'org.scijava.console.DefaultConsoleService' in 2 ms
[DEBUG] Creating service: org.scijava.event.DefaultEventHistory
[DEBUG] Created service 'org.scijava.event.DefaultEventHistory' in 2 ms
[DEBUG] Creating service: org.scijava.input.DefaultInputService
[DEBUG] Created service 'org.scijava.input.DefaultInputService' in 3 ms
[DEBUG] Creating service: org.scijava.io.DefaultDataHandleService
[DEBUG] Found 1 DataHandle plugins.
[DEBUG] Created service 'org.scijava.io.DefaultDataHandleService' in 1 ms
[DEBUG] Creating service: org.scijava.io.DefaultIOService
[DEBUG] Created service 'org.scijava.io.DefaultIOService' in 2 ms
[DEBUG] Creating service: org.scijava.io.DefaultRecentFileService
Mar 15, 2017 10:03:24 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0
x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[DEBUG] Created service 'org.scijava.io.DefaultRecentFileService' in 9 ms
[DEBUG] Creating service: org.scijava.main.DefaultMainService
[DEBUG] Created service 'org.scijava.main.DefaultMainService' in 0 ms
[DEBUG] Creating service: org.scijava.platform.DefaultPlatformService
[DEBUG] Creating service: org.scijava.platform.DefaultAppEventService
[DEBUG] Created service 'org.scijava.platform.DefaultAppEventService' in 0 ms
[DEBUG] Found 2 Platform plugins.
[DEBUG] Configuring platform: org.scijava.plugins.platforms.windows.WindowsPlatf
orm
[DEBUG] Configuring platform: org.scijava.platform.DefaultPlatform
[DEBUG] Created service 'org.scijava.platform.DefaultPlatformService' in 6 ms
[DEBUG] Creating service: org.scijava.plugins.scripting.jython.DefaultJythonServ
ice
[DEBUG] Created service 'org.scijava.plugins.scripting.jython.DefaultJythonServi
ce' in 1 ms
[DEBUG] Creating service: org.scijava.run.DefaultRunService
[DEBUG] Created service 'org.scijava.run.DefaultRunService' in 0 ms
[DEBUG] Creating service: org.scijava.script.DefaultScriptHeaderService
[DEBUG] Created service 'org.scijava.script.DefaultScriptHeaderService' in 0 ms
[DEBUG] Creating service: org.scijava.text.DefaultTextService
[DEBUG] Created service 'org.scijava.text.DefaultTextService' in 0 ms
[DEBUG] Creating service: org.scijava.tool.DefaultToolService
[DEBUG] Created service 'org.scijava.tool.DefaultToolService' in 3 ms
[DEBUG] Creating service: org.scijava.ui.DefaultUIService
[DEBUG] Created service 'org.scijava.ui.DefaultUIService' in 3 ms
[DEBUG] Creating service: org.scijava.ui.dnd.DefaultDragAndDropService
[DEBUG] Created service 'org.scijava.ui.dnd.DefaultDragAndDropService' in 2 ms
[DEBUG] Creating service: org.scijava.ui.swing.SwingIconService
[DEBUG] Created service 'org.scijava.ui.swing.SwingIconService' in 1 ms
[DEBUG] Creating service: org.scijava.ui.swing.script.DefaultLanguageSupportServ
ice
[DEBUG] Created service 'org.scijava.ui.swing.script.DefaultLanguageSupportServi
ce' in 0 ms
[DEBUG] Creating service: org.scijava.welcome.DefaultWelcomeService
[DEBUG] Created service 'org.scijava.welcome.DefaultWelcomeService' in 0 ms
[DEBUG] Creating service: org.scijava.widget.DefaultWidgetService
[DEBUG] Found 22 InputWidget plugins.
[DEBUG] Created service 'org.scijava.widget.DefaultWidgetService' in 1 ms
[DEBUG] Creating service: org.scijava.cache.DefaultCacheService
[DEBUG] Created service 'org.scijava.cache.DefaultCacheService' in 0 ms
[DEBUG] Creating service: io.scif.DefaultMetadataService
[DEBUG] Created service 'io.scif.DefaultMetadataService' in 0 ms
[DEBUG] Creating service: io.scif.codec.DefaultCodecService
[DEBUG] Created service 'io.scif.codec.DefaultCodecService' in 1 ms
[DEBUG] Creating service: io.scif.formats.qt.DefaultQTJavaService
[DEBUG] Created service 'io.scif.formats.qt.DefaultQTJavaService' in 3 ms
[DEBUG] Creating service: io.scif.formats.tiff.DefaultTiffService
[DEBUG] Created service 'io.scif.formats.tiff.DefaultTiffService' in 2 ms
[DEBUG] Creating service: io.scif.gui.DefaultGUIService
[DEBUG] Created service 'io.scif.gui.DefaultGUIService' in 1 ms
[DEBUG] Creating service: io.scif.img.DefaultImgUtilityService
[DEBUG] Created service 'io.scif.img.DefaultImgUtilityService' in 6 ms
[DEBUG] Creating service: io.scif.img.cell.cache.MapDBCache
[DEBUG] Creating service: io.scif.refs.DefaultRefManagerService
[DEBUG] Created service 'io.scif.refs.DefaultRefManagerService' in 0 ms
[DEBUG] Created service 'io.scif.img.cell.cache.MapDBCache' in 8 ms
[DEBUG] Creating service: io.scif.img.converters.DefaultPlaneConverterService
[DEBUG] Created service 'io.scif.img.converters.DefaultPlaneConverterService' in
 0 ms
[DEBUG] Creating service: io.scif.io.DefaultNIOService
[DEBUG] Created service 'io.scif.io.DefaultNIOService' in 1 ms
[DEBUG] Creating service: io.scif.ome.services.DefaultOMEMetadataService
Error while executing the main() method of class 'net.imagej.Main':
java.lang.IllegalArgumentException: Invalid service: io.scif.ome.services.Defaul
tOMEMetadataService
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.ja
va:280)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:231)

        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)

        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:166
)
        at org.scijava.Context.<init>(Context.java:278)
        at org.scijava.Context.<init>(Context.java:234)
        at org.scijava.Context.<init>(Context.java:174)
        at org.scijava.Context.<init>(Context.java:160)
        at net.imagej.ImageJ.<init>(ImageJ.java:76)
        at net.imagej.Main.launch(Main.java:61)
        at net.imagej.Main.main(Main.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Caused by: java.lang.NoClassDefFoundError: ome/xml/model/enums/EnumerationExcept
ion
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHel
per.java:302)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.ja
va:269)
        ... 17 more
Caused by: java.lang.ClassNotFoundException: ome.xml.model.enums.EnumerationExce
ption
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 23 more
```
May there be a quick solution available - like jumping back to a former version of the installer? Just to make the downloaded Fiji work again until this bug is fixed?

Cheers,
Robert

**Comment by Claus1** [comment]
The issue still exist when I try to compile latest Fiji jars with my program and new ImageJ() causes the problem.
I do not need bioformat . What I have to delete?

**Comment by ctrueden** [comment]
@Claus1 This is not the same issue. What you are talking about is something from source code; this issue was about the binary Fiji distribution not working out of the box. Please post your question on the [ImageJ Forum](http://forum.imagej.net/) and be specific. See [Bug reporting best practices](https://imagej.net/Bug_reporting_best_practices) for tips on how to write a good bug report.

**Comment by ctrueden** [comment]
@Claus1 Happy to help if you post your question on the ImageJ Forum. Again, please describe exactly what you are trying to do. From your writeup, I do not understand. I do actively support the core ImageJ libraries and the newest ones should definitely be working, provided you are deploying the JARs as intended.

**Comment by Claus1** [comment]
> Again, please describe exactly what you are trying to do. 
I try to use ImageJ from my program for filtering images without GUI. Using jar files from latest Fiji is not possible for that  because the initialization issue adove. 
May be it is wrong way to use ImageJ but binary reference in my project
<dependency>
    <groupId>net.imagej</groupId>
    <artifactId>imagej</artifactId>
    <version>2.0.0-rc-65</version>
</dependency>
is not resolved if I use instructions from the site. Some libraries are uknown for 
    "Maven repo"    at "http://repo1.maven.org/maven2",
    "Spring repo"   at "http://repo.springsource.org/libs-release",
    "Apache repo"   at "https://repository.apache.org/content/repositories/releases",
    "JBoss repo"    at "http://repository.jboss.org/nexus/content/groups/public-jboss",
    "Sonatype repo" at "https://oss.sonatype.org/content/repositories/releases",
    "Mvnrepository" at "http://mvnrepository.com/artifact"

Make clean project with this  dependency and will see.

**Comment by ctrueden** [comment]
@Claus1 Sorry that replying to this fell through the cracks for me.

From your list above, what is missing is the ImageJ Maven repository! https://maven.imagej.net/

A lot of the core ImageJ libraries, including `net.imagej:imagej`, are located in this repository. You need that repository in your `pom.xml` or similar build file for whatever build system you are using.

If you still need assistance, please push an [MCVE](https://stackoverflow.com/help/mcve) somewhere public so that we can see exactly how your project is set up, and determine in detail what is going wrong.

> is not resolved if I use instructions from the site.

Which instructions? Link, please.

**Comment by Claus1** [comment]
@ctrueden I avoided the issue by making jars from Fuji sources.
