### ISSUE TITLE
jython scripts do not run from console under Windows

### ISSUE THREAD

**Issue by TAdeJong** [imagej/imagej#237]
I am trying to run python scripts using the Jython interpreter of ImageJ under Windows 10, but this fails with the following error message:

```
> Fiji.app\ImageJ-win64.exe --headless --console helloworld.py

C:\Users\xxxx>Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Error while executing the main() method of class 'org.python.util.jython':
java.lang.UnsatisfiedLinkError: org.scijava.jython.shaded.org.fusesource.jansi.internal.CLibrary.init()V
        at org.scijava.jython.shaded.org.fusesource.jansi.internal.CLibrary.init(Native Method)
        at org.scijava.jython.shaded.org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:43)
        at org.scijava.jython.shaded.org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
        at org.scijava.jython.shaded.org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
        at org.python.jline.AnsiWindowsTerminal.detectAnsiSupport(AnsiWindowsTerminal.java:57)
        at org.python.jline.AnsiWindowsTerminal.<init>(AnsiWindowsTerminal.java:27)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.python.jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
        at org.python.jline.TerminalFactory.create(TerminalFactory.java:102)
        at org.python.jline.TerminalFactory.get(TerminalFactory.java:186)
        at org.python.jline.TerminalFactory.get(TerminalFactory.java:192)
        at org.python.jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
        at org.python.util.JLineConsole.install(JLineConsole.java:107)
        at org.python.core.Py.installConsole(Py.java:1744)
        at org.python.core.PySystemState.initConsole(PySystemState.java:1269)
        at org.python.core.PySystemState.doInitialize(PySystemState.java:1119)
        at org.python.core.PySystemState.initialize(PySystemState.java:1033)
        at org.python.core.PySystemState.initialize(PySystemState.java:989)
        at org.python.core.PySystemState.initialize(PySystemState.java:984)
        at org.python.util.jython.run(jython.java:263)
        at org.python.util.jython.main(jython.java:142)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
```
It does seem possible to run jython scripts with the '-macro' flag, but this doesn't allow for command line arguments...

Further details:
ImageJ1.52o, installed via Fiji, Windows 10 Enterprise, Java Version 8 Update 211

Helloworld.py:
```python
import os, sys
from ij import IJ, ImagePlus, ImageStack
from ij.plugin import FolderOpener

print(sys.argv)
```

**Comment by ctrueden** [comment]
Thank you for the very clear bug report, @TAdeJong.

Could you please try the following invocation?
```shell
ImageJ-win64.exe --ij2 --headless --console --run helloworld.py
```

Do you receive the same error in that case?

See the [Scripting Headless](https://imagej.net/Scripting_Headless) page for details.

**Comment by TAdeJong** [comment]
That does seem to work, including passing parameters:

```>Fiji.app\ImageJ-win64.exe --ij2 --headless --console --run helloworld.py "name='test'"

C:\Users\jongt>Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
([u'helloworld.py'], u'test')
```

With adapted helloworld.py:

```
#@String name
import os, sys
from ij import IJ, ImagePlus, ImageStack
from ij.plugin import FolderOpener

print(sys.argv, name)
```
It is however a shame that we can't simply use sys.argv in this case.
Also note for future reference that the double and single quotes are mandatoryly in this order.
