### ISSUE TITLE
Fiji won’t run even after a clean installation on Windows 10 (64-bit)

### ISSUE THREAD

**Issue by gyuregor** [imagej/imagej#245]
I just downloaded the newest Fiji version from the site. I have up-to-date Java 8 running on a 64bit Windows 10. When I double click on the exe, only the Fiji splash icon appears and then nothing happens. When I debugged, there were descriptions below. What should I do?

find_newest: searching 'C:\Users\조규찬\Desktop\Fiji.app/java' for 'jre/bin/server/jvm.dll'
find_newest: file not found: 'C:\Users\조규찬\Desktop\Fiji.app/java/jre/bin/server/jvm.dll'
find_newest: searching 'C:\Users\조규찬\Desktop\Fiji.app/java/win64' for 'jre/bin/server/jvm.dll'
find_newest: file not found: 'C:\Users\조규찬\Desktop\Fiji.app/java/win64/jre/bin/server/jvm.dll'
find_newest: searching 'C:\Users\조규찬\Desktop\Fiji.app/java/win64/jdk1.8.0_172' for 'jre/bin/server/jvm.dll'
find_newest: found a candidate: 'C:\Users\조규찬\Desktop\Fiji.app/java/win64/jdk1.8.0_172'
Detected ImageJ2
JRE not found in 'C:\Users\조규찬\Desktop\Fiji.app/jre'
JAVA_HOME contains a JRE: 'C:\Users\조규찬\Desktop\Fiji.app/java/win64/jdk1.8.0_172//jre'
Available RAM: 16269MB, using 3/4 of that: 12202MB
java -Dpython.cachedir.skip=true -Dplugins.dir=C:\\Users\\조규찬\\Desktop\\Fiji.app -Xmx12202m -Xincgc -XX:PermSize=128m -Djava.class.path=C:\\Users\\조규찬\\Desktop\\Fiji.app/jars/imagej-launcher-4.0.5.jar -Dimagej.dir=C:\\Users\\조규찬\\Desktop\\Fiji.app -Dij.dir=C:\\Users\\조규찬\\Desktop\\Fiji.app -Dfiji.dir=C:\\Users\\조규찬\\Desktop\\Fiji.app -Dfiji.defaultLibPath=bin/server/jvm.dll -Dfiji.executable=C:\\Users\\조규찬\\Desktop\\Fiji.app\\debug.exe -Dij.executable=C:\\Users\\조규찬\\Desktop\\Fiji.app\\debug.exe -Djava.library.path=C:\\Users\\조규찬\\Desktop\\Fiji.app/lib/win64;C:\\Users\\조규찬\\Desktop\\Fiji.app/mm/win64 -Dscijava.context.strict=false -Dij.debug=true -Dscijava.log.level=debug net.imagej.launcher.ClassLauncher -ijjarpath jars -ijjarpath plugins net.imagej.Main
Using JAVA_HOME C:\Users\조규찬\Desktop\Fiji.app/java/win64/jdk1.8.0_172//jre
Opening Java library C:\Users\조규찬\Desktop\Fiji.app/java/win64/jdk1.8.0_172//jre/bin/server/jvm.dll
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Adding option: -Djava.home=C:\Users\조규찬\Desktop\Fiji.app/java/win64/jdk1.8.0_172/
ij1.plugin.dirs: null
$HOME/.plugins: C:\Users\조규찬\.plugins does not exist
Launching main class net.imagej.Main with parameters []
Class loader = sun.misc.Launcher$AppClassLoader@c387f44
java.lang.ClassNotFoundException: net.imagej.Main
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:252)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
java.lang.ClassNotFoundException: imagej.Main
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:258)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Class 'net.imagej.Main' was not found

**Comment by ctrueden** [comment]
@gyuregor I have not seen this particular error before. It suggests that perhaps your installation of Fiji is incomplete. Is the file `C:\Users\조규찬\Desktop\Fiji.app\jars\imagej-2.0.0-rc-69.jar` present, with file size 10194 bytes? That JAR file is where the `net.imagej.Main` class lives.

**Comment by rimadoma** [comment]
A stab in the dark, but if the installation is complete, could be the Korean characters in the path?

**Comment by gyuregor** [comment]
> @gyuregor I have not seen this particular error before. It suggests that perhaps your installation of Fiji is incomplete. Is the file C:\Users\조규찬\Desktop\Fiji.app\jars\imagej-2.0.0-rc-69.jar present, with file size 10194 bytes? That JAR file is where the net.imagej.Main class lives.

imagej-2.0.0-rc-69.jar is present at the right place with size 10194 bytes....

**Comment by gyuregor** [comment]
> A stab in the dark, but if the installation is complete, could be the Korean characters in the path?

Korean characters are present in the path, because I set my user name in Korean characters. Could it be the problem?

**Comment by rimadoma** [comment]
It is possible. Could give a quick try installing in a different folder, like "C:/Test/"

**Comment by gyuregor** [comment]
> It is possible. Could give a quick try installing in a different folder, like "C:/Test/"

Fiji successfully runs just after I installed it in "C:/Test/" folder. Thank you so much for your advice!

**Comment by ctrueden** [comment]
@gyuregor I changed the title to reflect the problem. We can leave this issue open as a reminder to investigate and fix the problem in future. Thanks!
