### ISSUE TITLE
Java runtime errors on launch: namespace reporting not enabled

### ISSUE THREAD

**Issue by lindensmith** [imagej/imagej#249]
I'm getting a couple errors on launch of Fiji that seem to be keeping me from being able to update the updatesites list, too.

I'm using a Macbook Pro (mid 2014) running Mojave 10.14.6
ImageJ version is 2.0.0-rc-69/1.52u (same errors appeared on 1.52p)
Build 269a0ad53f

Java is Version 8 Update 221 (build 1.8.0_221-b11) and my Java control panel claims that my system has the recommended version of Java.

The error message I get is below in the code tags, and when I google it, it appears that the error isn't something I can fix by changing settings at my end.

`[ERROR] Error processing available update sites from ImageJ wiki
java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:/Library/Java/Extensions/saxon9he.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax
	at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:102)
	at org.scijava.util.XML.<init>(XML.java:142)
	at org.scijava.util.XML.<init>(XML.java:103)
	at net.imagej.util.MediaWikiClient.request(MediaWikiClient.java:234)
	at net.imagej.util.MediaWikiClient.query(MediaWikiClient.java:243)
	at net.imagej.util.MediaWikiClient.getPageSource(MediaWikiClient.java:109)
	at net.imagej.updater.util.AvailableSites.getAvailableSites(AvailableSites.java:79)
	at net.imagej.updater.util.AvailableSites.tryGetAvailableSites(AvailableSites.java:177)
	at net.imagej.updater.util.AvailableSites.initializeAndAddSites(AvailableSites.java:140)
	at net.imagej.ui.swing.updater.ImageJUpdater.refreshUpdateSites(ImageJUpdater.java:257)
	at net.imagej.ui.swing.updater.ImageJUpdater.run(ImageJUpdater.java:145)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
org.xml.sax.SAXException: Parser configuration problem: namespace reporting is not enabled
	at net.sf.saxon.event.ReceivingContentHandler.getNodeName(ReceivingContentHandler.java:383)
	at net.sf.saxon.event.ReceivingContentHandler.startElement(ReceivingContentHandler.java:291)
	at net.imagej.updater.XMLFileWriter.write(XMLFileWriter.java:156)
	at net.imagej.updater.FilesCollection.write(FilesCollection.java:439)
	at net.imagej.updater.util.AvailableSites.applySitesURLUpdates(AvailableSites.java:299)
	at net.imagej.ui.swing.updater.ImageJUpdater.refreshUpdateSites(ImageJUpdater.java:262)
	at net.imagej.ui.swing.updater.ImageJUpdater.run(ImageJUpdater.java:145)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by imagejan** [comment]
Thanks @lindensmith for reporting! Did you try this with a freshly downloaded Fiji? Also, what version of `imagej-updater.jar` do you have? And did you activate any update sites in addition to the default ones (ImageJ, Fiji, and Java-8)?

/cc @frauzufall @ctrueden

**Comment by lindensmith** [comment]
Yes, it was a fresh install. The version for imagej-updater.jar looks like 0.10.3.

I have a second machine that I also did a fresh install on that doesn't show the error.  It's a later Macbook pro (15", 2017) running 10.13.6 (High Sierra) and Java 8 Update 241, same version of Fiji/ImageJ.  (I just noticed the build number turned into a link and dropped a few characters.  It's `269a0ad53f`).  So I suspect it's a quirk of the Java version, but the Java control panel doesn't on the machine with the problem doesn't offer me an update option.  I'm poking into how to force it to update Java versions from the command line without inadvertently breaking something else.

**Comment by ctrueden** [comment]
@lindensmith Thanks for the report! Your error message mentions `/Library/Java/Extensions/saxon9he.jar`. On my macOS system, I have no files in the `/Library/Java/Extensions` folder. Probably you also should not have anything in there. If you do have files there, how did they get there? Did you install any Java extensions? Those take precedence over everything else, and are apparently messing up ImageJ here.
