### ISSUE TITLE
Color Thresholder causing java.awt.HeadlessException when run in headless mode

### ISSUE THREAD

**Issue by davidhampson** [imagej/imagej#250]
Greetings, I use ImageJ (FIJI) to run some headless processing in some .NET applications via a command line call. It has been working fine for a number of years, but since last week, it has been causing a headless exception. I have tried reverting to older builds on the ImageJ website to no avail. I have also tried running the macro on 3 different machines, (2 Windows 10, one CentOS 7).

To reproduce, simply try to run a macro containing 

run("Color Threshold...");

in headless mode. Any help is greatly appreciated. I have been bashing my head into the wall for days over this.

Here is the exception:

![image](https://user-images.githubusercontent.com/26553919/81600149-0064f480-937e-11ea-8443-4725306e5640.png)

I have tried giving Java up to 1024MB of memory, and opening the smallest image I can (1x1 pixel) to ensure that this is not a memory issue.

Thanks in advance!

**Comment by imagejan** [comment]
The [`ColorThresholder`](https://github.com/imagej/imagej1/blob/e383917297de467e3a08cc8cf4c0db18b565fd62/ij/plugin/frame/ColorThresholder.java) (part of `imagej1`) extends `java.awt.Frame` and, to my knowledge, was never compatible with headless mode. It's not one of the classes that [`ij1-patcher`](https://github.com/imagej/ij1-patcher) takes care of to make them headless-compatible.

In any case, when running from macro you should use the macro code generated by the plugin when pressing the *Macro* button. There should be no need to directly invoke `ColorThresholder` in a scripting context.

**Comment by davidhampson** [comment]
Thank you so much! Removing the line in question and keeping the macro generated code that came after it did the trick. The reason I had that line in my macro is because I made it with the macro record feature on, and in order to press the "Macro" button in the thresholder, I had to open the color thresholder window itself.

That being said, this is likely a useful issue to keep open as I know with relative certainty that the 
> run("Color Threshold...");
line didn't used to cause a crash (before about a week ago).
Maybe somehow I am just completely confused, but I had multiple macros that were working before that had that line in them.

Either way, thanks so much for the quick and helpful reply. 
Have a great day!

**Comment by ctrueden** [comment]
@davidhampson wrote:
> I know with relative certainty that the
>
> > run("Color Threshold...");
>
> line didn't used to cause a crash (before about a week ago).

I used [jgo](https://github.com/scijava/jgo) to test various versions of ImageJ 1.x back to 1.45a, and they all fail with `HeadlessException`:

<details>

```
$ cat macro.ijm
run("Color Threshold...");
$ jgo -Djava.awt.headless=true net.imagej:ij:1.52p -macro macro.ijm
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at ij.ImageJ.<init>(ImageJ.java:142)
	at ij.ImageJ.main(ImageJ.java:731)
$ jgo -Djava.awt.headless=true net.imagej:ij:1.52a -macro macro.ijm
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at ij.ImageJ.<init>(ImageJ.java:143)
	at ij.ImageJ.main(ImageJ.java:722)
$ jgo -Djava.awt.headless=true net.imagej:ij:1.51a -macro macro.ijm
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at ij.ImageJ.<init>(ImageJ.java:143)
	at ij.ImageJ.main(ImageJ.java:699)
$ jgo -Djava.awt.headless=true net.imagej:ij:1.50a -macro macro.ijm
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at ij.ImageJ.<init>(ImageJ.java:143)
	at ij.ImageJ.main(ImageJ.java:682)
$ jgo -Djava.awt.headless=true net.imagej:ij:1.49a -macro macro.ijm
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at ij.ImageJ.<init>(ImageJ.java:139)
	at ij.ImageJ.main(ImageJ.java:665)
$ jgo -Djava.awt.headless=true net.imagej:ij:1.45a -macro macro.ijm
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at ij.ImageJ.<init>(ImageJ.java:129)
	at ij.ImageJ.main(ImageJ.java:588)
```

</details>

I also tried a few with ImageJ2; e.g.:

<details>

```
$ jgo -Djava.awt.headless=true net.imagej:imagej-legacy+net.imagej:ij:1.51a+net.imagej:imagej -macro macro.ijm
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at ij.plugin.frame.PlugInFrame.<init>(PlugInFrame.java:13)
	at ij.plugin.frame.ColorThresholder.<init>(ColorThresholder.java:90)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at ij.IJ.runPlugIn(IJ.java:184)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at ij.IJ.run(IJ.java:296)
	at ij.IJ.run(IJ.java:271)
	at ij.macro.Functions.doRun(Functions.java:603)
	at ij.macro.Functions.doFunction(Functions.java:96)
	at ij.macro.Interpreter.doStatement(Interpreter.java:230)
	at ij.macro.Interpreter.doStatements(Interpreter.java:218)
	at ij.macro.Interpreter.run(Interpreter.java:115)
	at ij.macro.Interpreter.run(Interpreter.java:85)
	at ij.macro.Interpreter.run(Interpreter.java:96)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:155)
	at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:139)
	at ij.IJ.runMacroFile(IJ.java:147)
	at net.imagej.legacy.IJ1Helper$4.call(IJ1Helper.java:1165)
	at net.imagej.legacy.IJ1Helper$4.call(IJ1Helper.java:1161)
	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:1095)
	at net.imagej.legacy.IJ1Helper.runMacroFile(IJ1Helper.java:1161)
	at net.imagej.legacy.LegacyCommandline$Macro.handle(LegacyCommandline.java:185)
	at org.scijava.console.DefaultConsoleService.processArgs(DefaultConsoleService.java:102)
	at org.scijava.AbstractGateway.launch(AbstractGateway.java:106)
	at net.imagej.Main.main(Main.java:55)
```

</details>

I'd be surprised if that line ever worked when running headless.

That said, I'm glad you can just remove it and things work. :+1:

**Comment by davidhampson** [comment]
Bizarre! Wonder how it took so long before it became an issue for me... 
Thanks for checking it out, @ctrueden  :)
