### ISSUE TITLE
ImageConverter.convertToGray8 fall into java.awt.HeadlessException: null

### ISSUE THREAD

**Issue by dodokpeter** [imagej/ImageJ#261]
Hi I am using ImageJ for processing image in spring boot app. After calling ImageConverter.convertToGray8 it will hit Headless exception. As I intended to use this library with in rest api, there is no win feature. Here is the stack:
java.awt.HeadlessException: null
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.TextComponent.<init>(TextComponent.java:150)
	at java.desktop/java.awt.TextArea.<init>(TextArea.java:261)
	at java.desktop/java.awt.TextArea.<init>(TextArea.java:165)
	at ij.plugin.frame.Recorder.<clinit>(Recorder.java:33)
	at ij.ImagePlus.getProcessor(ImagePlus.java:986)
	at ij.process.ImageConverter.convertToGray8(ImageConverter.java:29)

**Comment by MatusJ** [comment]
I experience the same issue.

**Comment by rasband** [comment]
This bug is fixed in the latest ImageJ daily build (1.54m12). The commit is at https://github.com/imagej/ImageJ/commit/6542086be946883919724c6f57dab70dcdb68806.

**Comment by dodokpeter** [comment]
thank you very much
