### ISSUE TITLE
Mac Native M1 (arm64) support?

### ISSUE THREAD

**Issue by dstranathan** [imagej/imagej#283]
What is the status of Mac Native M1 (arm64) CPU support?

**Comment by psobolewskiPhD** [comment]
I've had success with Fiji, by downloading with no JRE and using a native JRE (e.g. Azul).
Works very well, nice speed up ~40% on a CPU computational task.
Some plugins that use compiled libs, etc. may need tweaks.
For example getting native CLIJ working resulted in an 8-fold speedup over Rosetta.
You can see some of my experience in this twitter thread:
https://twitter.com/psobolewskiPhD/status/1342494593082920960?s=20

**Comment by ctrueden** [comment]
@psobolewskiPhD JogAmp 2.4.0 (JOGL, JOCL, JOAL, Gluegen) was released earlier this month, and the release includes builds for mac-arm64. I should have new releases of imagej2 and fiji by the end of the week that include this release. This will be a big step toward ImageJ2 and Fiji supporting Mac M1 more comprehensively.

**Comment by psobolewskiPhD** [comment]
Cool, @ctrueden I'm happy to help test, though I'm not sure I've used those elements much previously (as I've been using Fiji with native arm64 JRE for a long time now)

**Comment by ctrueden** [comment]
@psobolewskiPhD I'm guessing that your current Fiji setup cannot use the 3D Viewer plugin. One easy way to test that is to do:

* File > Open Samples > T1 Head
* Image > Type > 8-bit
* Plugins > 3D Viewer

And see what happens.

My hope is that with the new JOGL 2.4.0, this will either begin working automatically, or else maybe with some small tweak somewhere.

**Comment by psobolewskiPhD** [comment]
> @psobolewskiPhD I'm guessing that your current Fiji setup cannot use the 3D Viewer plugin. One easy way to test that is to do:
> 
> * File > Open Samples > T1 Head
> * Image > Type > 8-bit
> * Plugins > 3D Viewer
> 
> And see what happens.

Correct:
```
(Fiji Is Just) ImageJ 2.9.0/1.53t; Java 11.0.11 [64-bit]; Mac OS X 13.1; 170MB of 10840MB (1%)
 
java.lang.UnsatisfiedLinkError: /private/var/folders/sy/y3_x27j14cxg3_vhycs6cr_h0000gn/T/jogamp_0000/file_cache/jln11471013896064159920/jln8880740635522233983/natives/macosx-universal/libgluegen_rt.dylib: dlopen(/private/var/folders/sy/y3_x27j14cxg3_vhycs6cr_h0000gn/T/jogamp_0000/file_cache/jln11471013896064159920/jln8880740635522233983/natives/macosx-universal/libgluegen_rt.dylib, 0x0001): tried: '/private/var/folders/sy/y3_x27j14cxg3_vhycs6cr_h0000gn/T/jogamp_0000/file_cache/jln11471013896064159920/jln8880740635522233983/natives/macosx-universal/libgluegen_rt.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/sy/y3_x27j14cxg3_vhycs6cr_h0000gn/T/jogamp_0000/file_cache/jln11471013896064159920/jln8880740635522233983/natives/macosx-universal/libgluegen_rt.dylib' (no such file), '/private/var/folders/sy/y3_x27j14cxg3_vhycs6cr_h0000gn/T/jogamp_0000/file_cache/jln11471013896064159920/jln8880740635522233983/natives/macosx-universal/libgluegen_rt.dylib
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:604)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:154)
	at jogamp.opengl.ThreadingImpl$1.run(ThreadingImpl.java:83)
	at jogamp.opengl.ThreadingImpl$1.run(ThreadingImpl.java:66)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at jogamp.opengl.ThreadingImpl.<clinit>(ThreadingImpl.java:66)
	at com.jogamp.opengl.Threading.disableSingleThreading(Threading.java:164)
	at org.scijava.java3d.JoglPipeline.initialize(JoglPipeline.java:130)
	at org.scijava.java3d.Pipeline.createPipeline(Pipeline.java:92)
	at org.scijava.java3d.MasterControl.loadLibraries(MasterControl.java:837)
	at org.scijava.java3d.VirtualUniverse.<clinit>(VirtualUniverse.java:274)
	at ij3d.ImageJ3DViewer.run(ImageJ3DViewer.java:60)
	at ij3d.ImageJ_3D_Viewer.run(ImageJ_3D_Viewer.java:37)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runPlugIn(IJ.java:203)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

> My hope is that with the new JOGL 2.4.0, this will either begin working automatically, or else maybe with some small tweak somewhere.

Sounds good!

**Comment by HSMSC** [comment]
> I've had success with Fiji, by downloading with no JRE and using a native JRE (e.g. Azul). Works very well, nice speed up ~40% on a CPU computational task. Some plugins that use compiled libs, etc. may need tweaks. For example getting native CLIJ working resulted in an 8-fold speedup over Rosetta. You can see some of my experience in this twitter thread: https://twitter.com/psobolewskiPhD/status/1342494593082920960?s=20

Hello, I am trying to follow this to run Fiji natively in my M1 Mac. I made a folder inside the no JRE Fiji app and named it java, then in a subfolder, named with my platform, I placed the JDK that downloaded from Azul. Sadly, Fiji is not starting up . I do not have much experience at this so I am likely missing a key step?

**Comment by HSMSC** [comment]
Thanks @ctrueden. That one runs but unfortunately something in it causes the plugin I need  to not function properly. So, this is why I was trying to run the unbundled Fiji, but maybe they are similar and this plug in will just not work on my Mac.

**Comment by psobolewskiPhD** [comment]
If a plugin isn't working i the arm64 Fiji, then a system arm64 Java won't help either.
You can try having everything in emulation, by downloading the x86 Fiji and running the plugin from there.
Basically, on the Apple Silicon macs, for Fiji/plugin to function everything has to either be native arm64 or everything has to be emulated. You can't mix and match.

**Comment by HSMSC** [comment]
ok, will try! Thank you!

**Comment by ctrueden** [comment]
@HSMSC Which plugin? I'd like to get issues filed in the right repositories on GitHub to track current limitations of Fiji on Apple silicon. It's probably due to native libraries not being provided for macos-arm64, or else unsigned native libraries not being loadable from within the hardened runtime.

**Comment by HSMSC** [comment]
@ctrueden The Fiji plugin for this pipeline below is the one that did not work when I tried the bundled Fiji for Apple Silicon: https://github.com/jeanollion/bacmman

I am back now to using just the Intel Fiji with Rosetta emulator (which I had already installed) and things are going better now. @psobolewskiPhD   Thank you both!

**Comment by ctrueden** [comment]
As of JOGL 2.6.0, the 3D Viewer and other OpenGL-based plugins now work correctly on macos-arm64 systems. I'm going to close this as complete, but if a fresh download of Fiji-Latest from https://fiji.sc/ still doesn't work on your modern macOS system, please feel welcome to reopen this issue, or file a new one with targeted details of what doesn't work.
